# Generated by Django 4.2.7 on 2023-11-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='tags',
        ),
        migrations.AddField(
            model_name='block',
            name='tags',
            field=models.ManyToManyField(related_name='blocks', to='ent.tag'),
        ),
    ]
